### PR TITLE
Prepare for release of `1.0.1`

### PR DESCRIPTION
**Pull request by gusmonod**
This would be the first version to support 3.12

@mariocj89 it looks like we have no PyPI automation, do you want to publish this version manually? Or should we take the opportunity to add PyPI publishing to the Github Actions?

### CODE REVIEW

**Comment by mariocj89** [comment]
If you have the energy to automate it, it would be great!!

**Comment by godlygeek** [comment]
@mariocj89 Would you mind making me and @pablogsal maintainers on the PyPI project?

I can't automate what I can't publish manually 😆

**Comment by godlygeek** [comment]
> @mariocj89 Would you mind making me and @pablogsal maintainers on the PyPI project?

You seem to have made Pablo a maintainer on https://pypi.org/project/pytest-pystack/ but I'm still not...

@pablogsal Can you pick this up if you have some time? I _think_ what I've got here should work, except that the `upload_pypi` stage has never been tested, because I can't set up a token (I'm an admin on this repo, but not a maintainer on pypi.org).

**Comment by godlygeek** [comment]
At the very least, the `build_dists` stage is succeeding, and the `dists` artifact contains a .whl and an sdist that should be good to publish to PyPI.

**Comment by godlygeek** [comment]
> You seem to have made Pablo a maintainer on https://pypi.org/project/pytest-pystack/ but I'm still not...

Hah, Pablo pointed out that that's because I needed to accept the invitation, and I never did, so it expired. Whoops! He reinvited me, so that's sorted now.

**Review by godlygeek — APPROVED** [review]
LGTM

**Comment by godlygeek** [comment]
Success:

image

That's released, and now we have release automation.

**Pull request merged**
